const products = [
  {
    id: 1,
    name: "Oud Mystère",
    brand: "Maison Noire",
    price: 89,
    scent: "Oriental",
    notes: "Oud, Ambre, Musc",
    ml: "50ml",
    tag: "Bestseller",
    description: "Un voyage olfactif profond et envoûtant. L'oud précieux se mêle à l'ambre doré pour créer une signature inoubliable.",
    color: "#8B5E3C",
    emoji: "🖤"
  },
  {
    id: 2,
    name: "Rose Céleste",
    brand: "Fleur de Paris",
    price: 74,
    scent: "Floral",
    notes: "Rose, Jasmin, Vanille",
    ml: "30ml",
    tag: "Nouveau",
    description: "La quintessence de la féminité. Une rose enveloppée de jasmin délicat et de vanille crémeuse.",
    color: "#C2185B",
    emoji: "🌹"
  },
  {
    id: 3,
    name: "Santal Doré",
    brand: "Luxe Essence",
    price: 112,
    scent: "Boisé",
    notes: "Santal, Cèdre, Patchouli",
    ml: "100ml",
    tag: "Premium",
    description: "Le santal le plus rare du monde sublimé par le cèdre noble. Un parfum pour les connaisseurs.",
    color: "#A0522D",
    emoji: "✨"
  },
  {
    id: 4,
    name: "Agrumes Royaux",
    brand: "Soleil d'Or",
    price: 58,
    scent: "Frais",
    notes: "Bergamote, Citron, Néroli",
    ml: "50ml",
    tag: "",
    description: "Une explosion de fraîcheur méditerranéenne. La bergamote vive rencontre le néroli délicat.",
    color: "#F59E0B",
    emoji: "🍋"
  },
  {
    id: 5,
    name: "Nuit Arabesque",
    brand: "Maison Noire",
    price: 95,
    scent: "Oriental",
    notes: "Cardamome, Rose, Oud",
    ml: "75ml",
    tag: "Exclusif",
    description: "Inspiré des nuits de Marrakech. La cardamome épicée s'entrelace avec la rose et l'oud mystérieux.",
    color: "#6B21A8",
    emoji: "🌙"
  },
  {
    id: 6,
    name: "Aqua Lumière",
    brand: "Bleu Azur",
    price: 63,
    scent: "Frais",
    notes: "Sel marin, Musc blanc, Iris",
    ml: "50ml",
    tag: "",
    description: "L'essence de l'océan capturée en flacon. Pur, lumineux et infiniment élégant.",
    color: "#0EA5E9",
    emoji: "💧"
  },
  {
    id: 7,
    name: "Velours Noir",
    brand: "Luxe Essence",
    price: 135,
    scent: "Oriental",
    notes: "Cuir, Fumée, Ambre noir",
    ml: "50ml",
    tag: "Exclusif",
    description: "Pour les âmes audacieuses. Un cuir sophistiqué enveloppé d'ambre sombre et d'une légère touche fumée.",
    color: "#1C1C1C",
    emoji: "🔥"
  },
  {
    id: 8,
    name: "Pivoine Ivoire",
    brand: "Fleur de Paris",
    price: 67,
    scent: "Floral",
    notes: "Pivoine, Muguet, Cèdre blanc",
    ml: "50ml",
    tag: "Nouveau",
    description: "La fraîcheur printanière en bouteille. La pivoine lumineuse danse avec le muguet délicat.",
    color: "#F9A8D4",
    emoji: "🌸"
  }
];
