const products = [
  {
    id: 1,
    name: "Black Orchid",
    brand: "Tom Ford",
    price: 89,
    scent: "Oriental",
    notes: "Black truffle, Ylang ylang, Dark chocolate",
    notesFr: "Truffe noire, Ylang ylang, Chocolat noir",
    ml: "50ml",
    tag: "Bestseller",
    description: "A luxurious and deeply sensual fragrance. Rich black orchid and dark chocolate intertwine with exotic spices in an opulent, unforgettable signature.",
    descriptionFr: "Un parfum luxueux et profondément sensuel. La riche orchidée noire et le chocolat noir s'entrelacent avec des épices exotiques dans une signature opulente et inoubliable.",
    color: "#8B5E3C",
    emoji: "🖤",
    image: "https://d3qyz78uf5x6r9.cloudfront.net/public/ACC_11/account/product/7036085/7036085_A1.jpg"
  },
  {
    id: 2,
    name: "ROSE IVOIRE DE CARON",
    brand: "CARON",
    price: 74,
    scent: "Floral",
    notes: "Rose, Jasmine, Vanilla",
    notesFr: "Rose, Jasmin, Vanille",
    ml: "30ml",
    tag: "Nouveau",
    description: "The quintessence of femininity. A rose wrapped in delicate jasmine and creamy vanilla.",
    descriptionFr: "La quintessence de la féminité. Une rose enveloppée de jasmin délicat et de vanille crémeuse.",
    color: "#C2185B",
    emoji: "🌹",
    image: "https://parisparfums.fr/6821-large_default/parfum-rose-ivoire-de-caron.jpg"
  },
  {
    id: 3,
    name: "Santal 33",
    brand: "Le Labo",
    price: 112,
    scent: "Boisé",
    notes: "Sandalwood, Cedar, Leather",
    notesFr: "Santal, Cèdre, Cuir",
    ml: "100ml",
    tag: "Premium",
    description: "The ultimate cult woody fragrance. Australian sandalwood meets Texan cedarwood in a bold, skin-like warmth that becomes uniquely yours.",
    descriptionFr: "Le parfum boisé culte par excellence. Le santal australien rencontre le cèdre texan dans une chaleur audacieuse qui devient uniquement la vôtre.",
    color: "#A0522D",
    emoji: "✨",
    image: "https://lelabo.ips.photos/lelabo-java/images/skus/100PS33100__PRODUCT_01--IMG_1200--SANTAL33-1687759440.jpg"
  },
  {
    id: 4,
    name: "GABRIELLE CHANEL",
    brand: "CHANEL",
    price: 58,
    scent: "Frais",
    notes: "Bergamot, Lemon, Neroli",
    notesFr: "Bergamote, Citron, Néroli",
    ml: "50ml",
    tag: "",
    description: "An explosion of Mediterranean freshness. Lively bergamot meets delicate neroli.",
    descriptionFr: "Une explosion de fraîcheur méditerranéenne. La bergamote vive rencontre le néroli délicat.",
    color: "#F59E0B",
    emoji: "🍋",
    image: "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=400&h=400&fit=crop&q=80"
  },
  {
    id: 5,
    name: "Black Opium",
    brand: "Yves Saint Laurent",
    price: 95,
    scent: "Oriental",
    notes: "Black coffee, White flowers, Vanilla",
    notesFr: "Café noir, Fleurs blanches, Vanille",
    ml: "75ml",
    tag: "Exclusif",
    description: "Addictive and rock-chic. A bold shot of black coffee entwines with delicate white flowers over a warm, sensual vanilla base.",
    descriptionFr: "Addictif et rock-chic. Un trait audacieux de café noir s'entrelace avec de délicates fleurs blanches sur une base de vanille chaude et sensuelle.",
    color: "#6B21A8",
    emoji: "🌙",
    image: "https://www.yslbeautyus.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dwf7216072/Black%20Opium%20Packshots/BO%20EDP/3365440787971.jpg"
  },
  {
    id: 6,
    name: "Bleu de Chanel",
    brand: "Bleu Azur",
    price: 63,
    scent: "Frais",
    notes: "Sea salt, White musk, Iris",
    notesFr: "Sel marin, Musc blanc, Iris",
    ml: "50ml",
    tag: "",
    description: "A bold, clean fragrance for the man who forges his own path. Citrus and incense meet dry woods in a resolutely modern signature.",
    descriptionFr: "Un parfum audacieux et pur pour l'homme qui trace sa propre voie. Agrumes et encens rencontrent des bois secs dans une signature résolument moderne.",
    color: "#0EA5E9",
    emoji: "💧",
    image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=400&h=400&fit=crop&q=80"
  },
  {
    id: 7,
    name: "Velours Noir",
    brand: "Yves Saint Laurent",
    price: 135,
    scent: "Oriental",
    notes: "Leather, Smoke, Black amber",
    notesFr: "Cuir, Fumée, Ambre noir",
    ml: "50ml",
    tag: "Exclusif",
    description: "For bold souls. A sophisticated leather wrapped in dark amber and a subtle smoky touch.",
    descriptionFr: "Pour les âmes audacieuses. Un cuir sophistiqué enveloppé d'ambre sombre et d'une légère touche fumée.",
    color: "#1C1C1C",
    emoji: "🔥",
    image: "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.40932.2x.avif"
  },
  {
    id: 8,
    name: "Flowerbomb",
    brand: "Viktor & Rolf",
    price: 67,
    scent: "Floral",
    notes: "Rose, Jasmine, Orchid",
    notesFr: "Rose, Jasmin, Orchidée",
    ml: "50ml",
    tag: "Nouveau",
    description: "An explosion of flowers that defies conventions. A lush bouquet of rose and jasmine detonates into a warm, irresistible sillage.",
    descriptionFr: "Une explosion de fleurs qui défie les conventions. Un bouquet luxuriant de rose et de jasmin détone en un sillage chaud et irrésistible.",
    color: "#F9A8D4",
    emoji: "🌸",
    image: "https://d3qyz78uf5x6r9.cloudfront.net/public/ACC_11/account/product/7032616/7032616_A1.jpg"
  }
];
